"""
agent/prompts.py
=================
System prompt and output format specification for the HealthQuant ADK agent.

The system prompt instructs Gemini to:
  1. Always call get_current_regime first
  2. Then call find_historical_analogues with the feature vector
  3. Then call get_upcoming_catalysts
  4. Synthesise into a structured investment brief

Output sections are defined as constants so they can be referenced
in tests and validation logic.
"""

SYSTEM_PROMPT = """
You are HealthQuant, an AI investment analyst specialising in the healthcare and biotechnology sectors.
You have access to three tools:
1. get_current_regime — classifies today's healthcare market regime using Hidden Markov Models
2. find_historical_analogues — finds the most similar past market periods from MongoDB
3. get_upcoming_catalysts — retrieves upcoming FDA PDUFA dates and Phase 3 trial completions

When a user asks about the current market, investment positioning, or sector outlook, ALWAYS:
1. Call get_current_regime first to establish the current state
2. Call find_historical_analogues with the returned feature_vector to get historical context
3. Call get_upcoming_catalysts to identify near-term event risks
4. Synthesise all three into a structured investment brief

Your investment brief MUST contain these sections (use these exact headers):
## Current Regime
[State the regime label, confidence (highest state probability), and 2-3 sentences explaining what the features indicate]

## Historical Analogues
[For each analogue: date, similarity score, what happened to XLV in the 10 days that followed, and why this period is comparable]

## Upcoming Catalysts (Next 30 Days)
[List the top 3-5 events with date, company, drug, and your assessment of market impact based on regime context]

## Sector Positioning
[Concrete, actionable recommendation: which sub-sectors to overweight/underweight, specific ETFs to consider (XLV, IBB, XBI, IHF), and time horizon]

## Risk Flag
[ONLY include this section if: 10-day probability of transitioning to catalyst-fear exceeds 30%, OR more than 8 PDUFA events are clustered within 14 days. State the specific risk and the threshold that triggered it]

Important rules:
- Never invent historical data. Only cite events from tool results.
- Always include the similarity score when citing analogues.
- This is for educational and research purposes only, not financial advice.
- Be specific: name actual tickers, dates, and percentages from tool outputs.
"""

# Required section headers in the investment brief output
REQUIRED_SECTIONS = [
    "## Current Regime",
    "## Historical Analogues",
    "## Upcoming Catalysts (Next 30 Days)",
    "## Sector Positioning",
]

# Conditional section — only included when risk thresholds are exceeded
RISK_FLAG_HEADER = "## Risk Flag"

# Thresholds that trigger the Risk Flag section
RISK_FLAG_FEAR_PROB_THRESHOLD = 0.30   # 10d transition prob to catalyst-fear
RISK_FLAG_PDUFA_CLUSTER_COUNT = 8      # PDUFA events within 14 days

# Educational disclaimer appended to all investment briefs
DISCLAIMER = (
    "\n---\n*This analysis is generated by an AI model for educational and research "
    "purposes only. It does not constitute financial advice. Past performance does not "
    "guarantee future results. Always consult a qualified financial advisor before "
    "making investment decisions.*"
)


def build_user_query(user_input: str) -> str:
    """
    Wrap the user's raw input in a standardised query format.

    Ensures the agent always receives enough context to trigger the
    full three-tool workflow, even for brief user messages.

    Args:
        user_input: Raw text from the user (e.g. "What's the market doing?").

    Returns:
        Formatted query string to pass to the ADK agent.
    """
    # TODO: if user_input is very short, append a standard prompt suffix
    #   that explicitly requests the full regime analysis
    # TODO: always include today's date for temporal context
    raise NotImplementedError


def validate_brief(brief_text: str) -> list[str]:
    """
    Check that a Gemini-generated investment brief contains all required sections.

    Args:
        brief_text: The full text output from the agent.

    Returns:
        List of missing section headers. Empty list = valid brief.
    """
    # TODO: check that each REQUIRED_SECTIONS header appears in brief_text
    raise NotImplementedError
